cdrive_path = '/home/hunteez/Workspace/github/selenium_academy_course/chromedriver'
mv_characters = 'https://www.marvel.com/characters'
next_button = '//*[@id="filter_grid-7"]/div/div[3]/div[3]/nav/ul/li[8]/span'
chr_name = '//*[@id="filter_grid-7"]/div/div[3]/div[2]/div[@class="mvl-card mvl-card--explore"]/a/div[2]/p'
chr_links = '//*[@id="filter_grid-7"]/div/div[3]/div[2]/div[@class="mvl-card mvl-card--explore"]/a'
bio_ctg = '//*[@id="two_column-4"]/div/div[3]/div[1]/div[2]/div[2]/div/ul[@class="railBioInfo"]/li/p'
bio_info = '//*[@id="two_column-4"]/div/div[3]/div[1]/div[2]/div[2]/div/ul[@class="railBioInfo"]/li/ul/li'